[logger]
label = "tombolo-viewer"
level = "debug"


[db]
host = "localhost"
port = 5432
username = "tombolo"
password = "*************"  # Excluded from git - set DB_PASSWORD environment variable
database = "tombolo-staging"
dialect = "postgres"
loglevel = 'debug' # Log level at which Sequelize logs are made

[jwt]
issuer = "Emu Analytics"
secret = "pm7ycGPshGXx"

[cors]
origin = "*"
credentials = true

[mapnik]
simplify_distance = 1
area_threshold = 50

[server]
baseUrl = "http://localhost:4200"
datasetCaching = false
slowTileLimit = 500 # ms
largeTileLimit = 100000 # bytes

[fileUpload]
maxFileSize = 52428800 # 50 MB

[client]
authEndpoint = "/accounts/api/v1"
socialMediaTitle = "My Tombolo Map"
socialMediaDescription = "Check out this amazing map I built with Tombolo!"
socialMediaTags = "tombolo, emuanalytics"
