[logger]
label = "tombolo-viewer"
level = "debug"


[db]
host = "localhost"
port = 5432
username = "tombolo"
password = "*************"  # Excluded from git - set DB_PASSWORD environment variable
database = "tombolo-staging"
dialect = "postgres"
loglevel = 'debug' # Log level at which Sequelize logs are made

[jwt]
issuer = "Emu Analytics"
secret = "pm7ycGPshGXx"

[cors]
origin = "*"
credentials = true

[mapnik]
simplify_distance = 1
area_threshold = 50

[server]
baseUrl = "http://localhost:4200"
datasetCaching = false
slowTileLimit = 500 # ms
largeTileLimit = 100000 # bytes

[fileUpload]
uploadPath = "/uploads"
maxFileSize = 52428800 # 50 MB

[auth]
sessionSecret = "fjdkjer994ks"

[auth.facebook]
clientId = "147217102619899"
clientSecret = "1deb1f9d17a53f41ddce510a9c47c109"
callback = "http://localhost:3000/auth/social/facebook/return#home"

[client]
authEndpoint = "/accounts/api/v1"
socialMediaTitle = "My Tombolo Map"
socialMediaDescription = "Check out this amazing map I built with Tombolo!"
socialMediaTags = "tombolo, emuanalytics"
googleAnalyticsUserId = "UA-79725616-5"


